// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/contrib/entproto/internal/entprototest/ent/autofieldmessage"
	"entgo.io/contrib/entproto/internal/entprototest/ent/predicate"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AutoFieldMessageQuery is the builder for querying AutoFieldMessage entities.
type AutoFieldMessageQuery struct {
	config
	ctx        *QueryContext
	order      []autofieldmessage.OrderOption
	inters     []Interceptor
	predicates []predicate.AutoFieldMessage
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AutoFieldMessageQuery builder.
func (afmq *AutoFieldMessageQuery) Where(ps ...predicate.AutoFieldMessage) *AutoFieldMessageQuery {
	afmq.predicates = append(afmq.predicates, ps...)
	return afmq
}

// Limit the number of records to be returned by this query.
func (afmq *AutoFieldMessageQuery) Limit(limit int) *AutoFieldMessageQuery {
	afmq.ctx.Limit = &limit
	return afmq
}

// Offset to start from.
func (afmq *AutoFieldMessageQuery) Offset(offset int) *AutoFieldMessageQuery {
	afmq.ctx.Offset = &offset
	return afmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (afmq *AutoFieldMessageQuery) Unique(unique bool) *AutoFieldMessageQuery {
	afmq.ctx.Unique = &unique
	return afmq
}

// Order specifies how the records should be ordered.
func (afmq *AutoFieldMessageQuery) Order(o ...autofieldmessage.OrderOption) *AutoFieldMessageQuery {
	afmq.order = append(afmq.order, o...)
	return afmq
}

// First returns the first AutoFieldMessage entity from the query.
// Returns a *NotFoundError when no AutoFieldMessage was found.
func (afmq *AutoFieldMessageQuery) First(ctx context.Context) (*AutoFieldMessage, error) {
	nodes, err := afmq.Limit(1).All(setContextOp(ctx, afmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{autofieldmessage.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) FirstX(ctx context.Context) *AutoFieldMessage {
	node, err := afmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AutoFieldMessage ID from the query.
// Returns a *NotFoundError when no AutoFieldMessage ID was found.
func (afmq *AutoFieldMessageQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = afmq.Limit(1).IDs(setContextOp(ctx, afmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{autofieldmessage.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) FirstIDX(ctx context.Context) int {
	id, err := afmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AutoFieldMessage entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AutoFieldMessage entity is found.
// Returns a *NotFoundError when no AutoFieldMessage entities are found.
func (afmq *AutoFieldMessageQuery) Only(ctx context.Context) (*AutoFieldMessage, error) {
	nodes, err := afmq.Limit(2).All(setContextOp(ctx, afmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{autofieldmessage.Label}
	default:
		return nil, &NotSingularError{autofieldmessage.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) OnlyX(ctx context.Context) *AutoFieldMessage {
	node, err := afmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AutoFieldMessage ID in the query.
// Returns a *NotSingularError when more than one AutoFieldMessage ID is found.
// Returns a *NotFoundError when no entities are found.
func (afmq *AutoFieldMessageQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = afmq.Limit(2).IDs(setContextOp(ctx, afmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{autofieldmessage.Label}
	default:
		err = &NotSingularError{autofieldmessage.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) OnlyIDX(ctx context.Context) int {
	id, err := afmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AutoFieldMessages.
func (afmq *AutoFieldMessageQuery) All(ctx context.Context) ([]*AutoFieldMessage, error) {
	ctx = setContextOp(ctx, afmq.ctx, ent.OpQueryAll)
	if err := afmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AutoFieldMessage, *AutoFieldMessageQuery]()
	return withInterceptors[[]*AutoFieldMessage](ctx, afmq, qr, afmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) AllX(ctx context.Context) []*AutoFieldMessage {
	nodes, err := afmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AutoFieldMessage IDs.
func (afmq *AutoFieldMessageQuery) IDs(ctx context.Context) (ids []int, err error) {
	if afmq.ctx.Unique == nil && afmq.path != nil {
		afmq.Unique(true)
	}
	ctx = setContextOp(ctx, afmq.ctx, ent.OpQueryIDs)
	if err = afmq.Select(autofieldmessage.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) IDsX(ctx context.Context) []int {
	ids, err := afmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (afmq *AutoFieldMessageQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, afmq.ctx, ent.OpQueryCount)
	if err := afmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, afmq, querierCount[*AutoFieldMessageQuery](), afmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) CountX(ctx context.Context) int {
	count, err := afmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (afmq *AutoFieldMessageQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, afmq.ctx, ent.OpQueryExist)
	switch _, err := afmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (afmq *AutoFieldMessageQuery) ExistX(ctx context.Context) bool {
	exist, err := afmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AutoFieldMessageQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (afmq *AutoFieldMessageQuery) Clone() *AutoFieldMessageQuery {
	if afmq == nil {
		return nil
	}
	return &AutoFieldMessageQuery{
		config:     afmq.config,
		ctx:        afmq.ctx.Clone(),
		order:      append([]autofieldmessage.OrderOption{}, afmq.order...),
		inters:     append([]Interceptor{}, afmq.inters...),
		predicates: append([]predicate.AutoFieldMessage{}, afmq.predicates...),
		// clone intermediate query.
		sql:  afmq.sql.Clone(),
		path: afmq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AutoFieldMessage.Query().
//		GroupBy(autofieldmessage.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (afmq *AutoFieldMessageQuery) GroupBy(field string, fields ...string) *AutoFieldMessageGroupBy {
	afmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AutoFieldMessageGroupBy{build: afmq}
	grbuild.flds = &afmq.ctx.Fields
	grbuild.label = autofieldmessage.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.AutoFieldMessage.Query().
//		Select(autofieldmessage.FieldName).
//		Scan(ctx, &v)
func (afmq *AutoFieldMessageQuery) Select(fields ...string) *AutoFieldMessageSelect {
	afmq.ctx.Fields = append(afmq.ctx.Fields, fields...)
	sbuild := &AutoFieldMessageSelect{AutoFieldMessageQuery: afmq}
	sbuild.label = autofieldmessage.Label
	sbuild.flds, sbuild.scan = &afmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AutoFieldMessageSelect configured with the given aggregations.
func (afmq *AutoFieldMessageQuery) Aggregate(fns ...AggregateFunc) *AutoFieldMessageSelect {
	return afmq.Select().Aggregate(fns...)
}

func (afmq *AutoFieldMessageQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range afmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, afmq); err != nil {
				return err
			}
		}
	}
	for _, f := range afmq.ctx.Fields {
		if !autofieldmessage.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if afmq.path != nil {
		prev, err := afmq.path(ctx)
		if err != nil {
			return err
		}
		afmq.sql = prev
	}
	return nil
}

func (afmq *AutoFieldMessageQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AutoFieldMessage, error) {
	var (
		nodes = []*AutoFieldMessage{}
		_spec = afmq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AutoFieldMessage).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AutoFieldMessage{config: afmq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, afmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (afmq *AutoFieldMessageQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := afmq.querySpec()
	_spec.Node.Columns = afmq.ctx.Fields
	if len(afmq.ctx.Fields) > 0 {
		_spec.Unique = afmq.ctx.Unique != nil && *afmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, afmq.driver, _spec)
}

func (afmq *AutoFieldMessageQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(autofieldmessage.Table, autofieldmessage.Columns, sqlgraph.NewFieldSpec(autofieldmessage.FieldID, field.TypeInt))
	_spec.From = afmq.sql
	if unique := afmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if afmq.path != nil {
		_spec.Unique = true
	}
	if fields := afmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, autofieldmessage.FieldID)
		for i := range fields {
			if fields[i] != autofieldmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := afmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := afmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := afmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := afmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (afmq *AutoFieldMessageQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(afmq.driver.Dialect())
	t1 := builder.Table(autofieldmessage.Table)
	columns := afmq.ctx.Fields
	if len(columns) == 0 {
		columns = autofieldmessage.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if afmq.sql != nil {
		selector = afmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if afmq.ctx.Unique != nil && *afmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range afmq.predicates {
		p(selector)
	}
	for _, p := range afmq.order {
		p(selector)
	}
	if offset := afmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := afmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AutoFieldMessageGroupBy is the group-by builder for AutoFieldMessage entities.
type AutoFieldMessageGroupBy struct {
	selector
	build *AutoFieldMessageQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (afmgb *AutoFieldMessageGroupBy) Aggregate(fns ...AggregateFunc) *AutoFieldMessageGroupBy {
	afmgb.fns = append(afmgb.fns, fns...)
	return afmgb
}

// Scan applies the selector query and scans the result into the given value.
func (afmgb *AutoFieldMessageGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, afmgb.build.ctx, ent.OpQueryGroupBy)
	if err := afmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AutoFieldMessageQuery, *AutoFieldMessageGroupBy](ctx, afmgb.build, afmgb, afmgb.build.inters, v)
}

func (afmgb *AutoFieldMessageGroupBy) sqlScan(ctx context.Context, root *AutoFieldMessageQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(afmgb.fns))
	for _, fn := range afmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*afmgb.flds)+len(afmgb.fns))
		for _, f := range *afmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*afmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := afmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AutoFieldMessageSelect is the builder for selecting fields of AutoFieldMessage entities.
type AutoFieldMessageSelect struct {
	*AutoFieldMessageQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (afms *AutoFieldMessageSelect) Aggregate(fns ...AggregateFunc) *AutoFieldMessageSelect {
	afms.fns = append(afms.fns, fns...)
	return afms
}

// Scan applies the selector query and scans the result into the given value.
func (afms *AutoFieldMessageSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, afms.ctx, ent.OpQuerySelect)
	if err := afms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AutoFieldMessageQuery, *AutoFieldMessageSelect](ctx, afms.AutoFieldMessageQuery, afms, afms.inters, v)
}

func (afms *AutoFieldMessageSelect) sqlScan(ctx context.Context, root *AutoFieldMessageQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(afms.fns))
	for _, fn := range afms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*afms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := afms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
