// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/contrib/entproto/internal/entprototest/ent/autofieldmessage"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// AutoFieldMessage is the model entity for the AutoFieldMessage schema.
type AutoFieldMessage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Age holds the value of the "age" field.
	Age          int32 `json:"age,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AutoFieldMessage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case autofieldmessage.FieldID, autofieldmessage.FieldAge:
			values[i] = new(sql.NullInt64)
		case autofieldmessage.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AutoFieldMessage fields.
func (afm *AutoFieldMessage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case autofieldmessage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			afm.ID = int(value.Int64)
		case autofieldmessage.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				afm.Name = value.String
			}
		case autofieldmessage.FieldAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field age", values[i])
			} else if value.Valid {
				afm.Age = int32(value.Int64)
			}
		default:
			afm.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AutoFieldMessage.
// This includes values selected through modifiers, order, etc.
func (afm *AutoFieldMessage) Value(name string) (ent.Value, error) {
	return afm.selectValues.Get(name)
}

// Update returns a builder for updating this AutoFieldMessage.
// Note that you need to call AutoFieldMessage.Unwrap() before calling this method if this AutoFieldMessage
// was returned from a transaction, and the transaction was committed or rolled back.
func (afm *AutoFieldMessage) Update() *AutoFieldMessageUpdateOne {
	return NewAutoFieldMessageClient(afm.config).UpdateOne(afm)
}

// Unwrap unwraps the AutoFieldMessage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (afm *AutoFieldMessage) Unwrap() *AutoFieldMessage {
	_tx, ok := afm.config.driver.(*txDriver)
	if !ok {
		panic("ent: AutoFieldMessage is not a transactional entity")
	}
	afm.config.driver = _tx.drv
	return afm
}

// String implements the fmt.Stringer.
func (afm *AutoFieldMessage) String() string {
	var builder strings.Builder
	builder.WriteString("AutoFieldMessage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", afm.ID))
	builder.WriteString("name=")
	builder.WriteString(afm.Name)
	builder.WriteString(", ")
	builder.WriteString("age=")
	builder.WriteString(fmt.Sprintf("%v", afm.Age))
	builder.WriteByte(')')
	return builder.String()
}

// AutoFieldMessages is a parsable slice of AutoFieldMessage.
type AutoFieldMessages []*AutoFieldMessage
